from PluginTaskAggregate import PluginTaskAggregate
from PluginTaskPlot import PluginTaskPlot
from PluginTaskSubset import PluginTaskSubset
from PluginTaskThreshold import PluginTaskThreshold
from PluginTaskUnitConversion import PluginTaskUnitConversion
from PluginTaskPercentile import PluginTaskPercentile
from PluginTaskDelta import PluginTaskDelta
from PluginTaskClimatology import PluginTaskClimatology
