from PluginTaskAggregate import PluginTaskAggregate
from PluginTaskPlot import PluginTaskPlot
from PluginTaskSubset import PluginTaskSubset
from PluginTaskThreshold import PluginTaskThreshold
from PluginTaskUnitConversion import PluginTaskUnitConversion